package com.attendance.bean;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendancedetails generated by hbm2java
 */
@Entity
@Table(name = "attendancedetails", catalog = "test")
public class AttendanceDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long attendanceId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "employee_id", referencedColumnName = "employee_id", nullable = false),
			@JoinColumn(name = "access_cardno", referencedColumnName = "access_cardno", nullable = false) })
	private Employee employee;
	private Date swipeIn;
	private Date swipeOut;
	private Integer totalHours;
	private Long machineId;

	public AttendanceDetails() {
	}

	public AttendanceDetails(long attendanceId, Employee employee) {
		this.attendanceId = attendanceId;
		this.employee = employee;
	}

	public AttendanceDetails(long attendanceId, Employee employee, Date swipeIn, Date swipeOut, Integer totalHours,
			Long machineId) {
		this.attendanceId = attendanceId;
		this.employee = employee;
		this.swipeIn = swipeIn;
		this.swipeOut = swipeOut;
		this.totalHours = totalHours;
		this.machineId = machineId;
	}

	@Id

	@Column(name = "attendance_id", unique = true, nullable = false)
	public long getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(long attendanceId) {
		this.attendanceId = attendanceId;
	}

	
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "swipe_in", length = 19)
	public Date getSwipeIn() {
		return this.swipeIn;
	}

	public void setSwipeIn(Date swipeIn) {
		this.swipeIn = swipeIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "swipe_out", length = 19)
	public Date getSwipeOut() {
		return this.swipeOut;
	}

	public void setSwipeOut(Date swipeOut) {
		this.swipeOut = swipeOut;
	}

	@Column(name = "total_hours")
	public Integer getTotalHours() {
		return this.totalHours;
	}

	public void setTotalHours(Integer totalHours) {
		this.totalHours = totalHours;
	}

	@Column(name = "machine_id")
	public Long getMachineId() {
		return this.machineId;
	}

	public void setMachineId(Long machineId) {
		this.machineId = machineId;
	}

}
