package com.attendance.bean;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "test")
public class Employee implements java.io.Serializable {

	private EmployeeId id;
	private String firstname;
	private String lastname;
	private String activeStatus;
	private String employeetype;
	private Set attendancedetailses = new HashSet(0);

	public Employee() {
	}

	public Employee(EmployeeId id, String firstname, String lastname, String activeStatus, String employeetype) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.activeStatus = activeStatus;
		this.employeetype = employeetype;
	}

	public Employee(EmployeeId id, String firstname, String lastname, String activeStatus, String employeetype,
			Set attendancedetailses) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.activeStatus = activeStatus;
		this.employeetype = employeetype;
		this.attendancedetailses = attendancedetailses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeId", column = @Column(name = "employee_id", nullable = false)),
			@AttributeOverride(name = "accessCardno", column = @Column(name = "access_cardno", nullable = false)) })
	public EmployeeId getId() {
		return this.id;
	}

	public void setId(EmployeeId id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "active_status", nullable = false, length = 3)
	public String getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "employeetype", nullable = false, length = 20)
	public String getEmployeetype() {
		return this.employeetype;
	}

	public void setEmployeetype(String employeetype) {
		this.employeetype = employeetype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set getAttendancedetailses() {
		return this.attendancedetailses;
	}

	public void setAttendancedetailses(Set attendancedetailses) {
		this.attendancedetailses = attendancedetailses;
	}

}
