package com.attendance.bean;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeId generated by hbm2java
 */
@Embeddable
public class EmployeeId implements java.io.Serializable {

	private long employeeId;
	private long accessCardno;

	public EmployeeId() {
	}

	public EmployeeId(long employeeId, long accessCardno) {
		this.employeeId = employeeId;
		this.accessCardno = accessCardno;
	}

	@Column(name = "employee_id", nullable = false)
	public long getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(long employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "access_cardno", nullable = false)
	public long getAccessCardno() {
		return this.accessCardno;
	}

	public void setAccessCardno(long accessCardno) {
		this.accessCardno = accessCardno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeId))
			return false;
		EmployeeId castOther = (EmployeeId) other;

		return (this.getEmployeeId() == castOther.getEmployeeId())
				&& (this.getAccessCardno() == castOther.getAccessCardno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEmployeeId();
		result = 37 * result + (int) this.getAccessCardno();
		return result;
	}

}
