package com.attendance.bean;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Machinedetails generated by hbm2java
 */
@Entity
@Table(name = "machinedetails", catalog = "test")
public class Machinedetails implements java.io.Serializable {

	private long machineId;
	private String location;
	private String machineType;

	public Machinedetails() {
	}

	public Machinedetails(long machineId, String location, String machineType) {
		this.machineId = machineId;
		this.location = location;
		this.machineType = machineType;
	}

	@Id

	@Column(name = "machine_id", unique = true, nullable = false)
	public long getMachineId() {
		return this.machineId;
	}

	public void setMachineId(long machineId) {
		this.machineId = machineId;
	}

	@Column(name = "location", nullable = false, length = 20)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "machine_type", nullable = false, length = 20)
	public String getMachineType() {
		return this.machineType;
	}

	public void setMachineType(String machineType) {
		this.machineType = machineType;
	}

}
